import { ORG } from "../lib/org";
import type { Role } from "../lib/auth";

/**
 * Yazdırma anteti ve alt künyesi. Ekranda görünmez (`print-only`), yalnızca
 * PDF/yazdırma çıktısında çıkar.
 *
 * Amaç: çıktının ekran görüntüsü gibi değil, belge gibi görünmesi. Antet ilk
 * sayfada bir kez; alt künye `position: fixed` olduğu için her sayfada tekrar
 * eder (Chrome davranışı), tablo başlıkları da `thead` sayesinde tekrarlar.
 */

const ROLE_LABEL: Record<Role, string> = {
  ADMIN: "Admin",
  MANAGER: "Manager",
  INSTRUCTOR: "Instructor",
  USER: "Employee",
  CUSTOMER: "Customer",
};

function stamp(): string {
  const d = new Date();
  const p = (n: number) => String(n).padStart(2, "0");
  return `${p(d.getDate())}.${p(d.getMonth() + 1)}.${d.getFullYear()} ${p(d.getHours())}:${p(
    d.getMinutes()
  )}`;
}

export function ReportLetterhead({
  title,
  subtitle,
  userName,
  role,
  scope,
}: {
  title: string;
  subtitle?: string;
  userName?: string;
  role: Role;
  /** Verinin kapsamı — örn. departman adı. Rapor neyin kaydı olduğunu söylemeli. */
  scope?: string;
}) {
  return (
    <div className="print-only report-head">
      <div className="rh-top">
        <img src="/Logo.png" alt="" className="rh-logo" />
        <div className="rh-org">
          <div className="rh-org-name">{ORG.name}</div>
          <div className="rh-org-sub">{ORG.approvalLine}</div>
        </div>
        {/* Form künyesi antette: sabit alt künye çok sayfalı çıktıda tablonun
            üstüne biniyordu, buraya alındı. */}
        <div className="rh-doc">
          <div>
            Form No: <b>{ORG.footer.formNo}</b>
          </div>
          <div>
            Rev. {ORG.footer.revisionNo} · {ORG.footer.revisionDate}
          </div>
        </div>
      </div>

      <div className="rh-title-row">
        <h1 className="rh-title">{title}</h1>
        {subtitle && <p className="rh-sub">{subtitle}</p>}
      </div>

      <table className="rh-meta">
        <tbody>
          <tr>
            <th>Generated</th>
            <td>{stamp()}</td>
            <th>Generated by</th>
            <td>
              {userName || "—"} · {ROLE_LABEL[role]}
            </td>
          </tr>
          <tr>
            <th>Scope</th>
            <td colSpan={3}>{scope || "All records visible to this account"}</td>
          </tr>
        </tbody>
      </table>
    </div>
  );
}

/**
 * Belgenin sonundaki künye. Normal akışta durur — `position: fixed` ile her
 * sayfaya bastırmayı denemiştik, çok sayfalı çıktıda tablonun üstüne biniyordu.
 * Form numarası artık antette, her sayfanın başında.
 */
export function ReportFootnote() {
  const f = ORG.footer;
  return (
    <div className="print-only report-foot">
      <span>{ORG.legalFooter} — generated by the BonAir Academy system</span>
      <span>
        Form No: {f.formNo} / Revision No: {f.revisionNo} / Revision Date: {f.revisionDate}
      </span>
    </div>
  );
}
